[window]
title = "Alacritty"
dynamic_title = true
decorations = "Full"

[font]
normal = { family = "FiraMono", style = "Regular"}
bold = {family = "FiraMono"}
italic = {family = "FiraMono"}
bold_italic = {family = "FiraMono"}
size = 7

[colors]
primary.background = '0xffffff'
